services:
  zookeeper:
    image: bitnamilegacy/zookeeper:3.8
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka-1:
    image: bitnamilegacy/kafka:3.4
    restart: on-failure
    ports:
      - "9092:9092"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-1:29092,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper

  kafka-2:
    image: bitnamilegacy/kafka:3.4
    restart: on-failure
    ports:
      - "9093:9093"
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_LISTENERS: INTERNAL://:29093,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka-2:29093,EXTERNAL://localhost:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper

  kafka-init:
    image: bitnamilegacy/kafka:3.4
    depends_on:
      - kafka-1
      - kafka-2
    volumes:
      - ./scripts:/scripts
    command: ["/bin/sh", "/scripts/create-topic.sh"]

  order:
    image: node:20-alpine
    working_dir: /app
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      KAFKA_BROKERS: kafka-1:29092,kafka-2:29093
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "corepack enable && yarn install --frozen-lockfile && yarn workspace order start"
    depends_on:
      kafka-init:
        condition: service_completed_successfully

  notification:
    image: node:20-alpine
    working_dir: /app
    restart: on-failure
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      KAFKA_BROKERS: kafka-1:29092,kafka-2:29093
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "corepack enable && yarn install --frozen-lockfile && yarn workspace notification start"
    depends_on:
      kafka-init:
        condition: service_completed_successfully

  analytics:
    image: node:20-alpine
    working_dir: /app
    restart: on-failure
    ports:
      - "3003:3003"
    environment:
      PORT: 3003
      KAFKA_BROKERS: kafka-1:29092,kafka-2:29093
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "corepack enable && yarn install --frozen-lockfile && yarn workspace analytics start"
    depends_on:
      kafka-init:
        condition: service_completed_successfully
